APP:
  REST_HOST: localhost
  ENVIRONMENT: TEST
  PORT: 5000
  ACCESS-CONTROL-ALLOW-ORIGIN: 'http://localhost'
  
MYSQL_DATABASE:
  USER: root
  PASSWORD: root
  HOST: localhost
  PORT: 3600
  DB_NAME: athletes_db